"""made certain columns in User table nullable

Revision ID: 0c0e05c95a8f
Revises: 8eb5c2867aa3
Create Date: 2021-05-16 14:41:50.406075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c0e05c95a8f'
down_revision = '8eb5c2867aa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('profile_img',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('profile_img',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
