"""Added post and community column in the User table in order to display all what user have post on the Post and Community Table. Add Community table

Revision ID: 35feeb7fd877
Revises: 69e0bea6a0b0
Create Date: 2021-02-05 15:52:19.990197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35feeb7fd877'
down_revision = '69e0bea6a0b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_board',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('community_board', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_board_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community_board', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_board_timestamp'))

    op.drop_table('community_board')
    # ### end Alembic commands ###
