"""Added first name, last name, and phone number to User Table

Revision ID: 69e0bea6a0b0
Revises: f6094dbece64
Create Date: 2020-12-23 03:44:02.043200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69e0bea6a0b0'
down_revision = 'f6094dbece64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstName', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('lastName', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('phoneNumber', sa.String(length=11), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=60), nullable=True))
        batch_op.drop_column('phoneNumber')
        batch_op.drop_column('lastName')
        batch_op.drop_column('firstName')

    # ### end Alembic commands ###
