"""Update Community Board model to have title column

Revision ID: 8eb5c2867aa3
Revises: 3fc03f7e12e7
Create Date: 2021-04-30 10:49:18.566443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eb5c2867aa3'
down_revision = '3fc03f7e12e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community_board', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=True))
        batch_op.alter_column('post_img',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community_board', schema=None) as batch_op:
        batch_op.alter_column('post_img',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('title')

    # ### end Alembic commands ###
