"""fixed type for text notification in User table

Revision ID: a965050cb096
Revises: 0c0e05c95a8f
Create Date: 2021-06-27 15:37:16.056579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a965050cb096'
down_revision = '0c0e05c95a8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_notification', sa.Boolean(), nullable=True))
        batch_op.drop_column('test_notification')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_notification', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('text_notification')

    # ### end Alembic commands ###
