"""Add start and end time in the Post table

Revision ID: ab61610ec961
Revises: dd7d10089751
Create Date: 2020-11-03 15:59:02.307446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab61610ec961'
down_revision = 'dd7d10089751'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('start', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('start')
        batch_op.drop_column('end')

    # ### end Alembic commands ###
