"""Added name in User Column and Added name as a column and foreign key in Post Table

Revision ID: d6e24c620da8
Revises: a29e68516fd6
Create Date: 2020-10-18 18:10:40.558665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6e24c620da8'
down_revision = 'a29e68516fd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('name', sa.String(length=60), nullable=True))
    op.create_foreign_key(None, 'post', 'user', ['name'], ['name'])
    op.add_column('user', sa.Column('name', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'name')
    # ### end Alembic commands ###
