"""Change Post table to Maintenance, Created the CommunityBoard table, and removed author column from Maintenance and Event table

Revision ID: d9bd465aa6eb
Revises: 35feeb7fd877
Create Date: 2021-02-09 13:31:16.597902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9bd465aa6eb'
down_revision = '35feeb7fd877'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('start', sa.Time(), nullable=True),
    sa.Column('end', sa.Time(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index('ix_post_timestamp')

    op.drop_table('post')
    with op.batch_alter_table('community_board', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.String(), nullable=True))
        batch_op.drop_column('post')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=60), nullable=True))

    with op.batch_alter_table('community_board', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('body')

    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.VARCHAR(length=120), nullable=True),
    sa.Column('author', sa.VARCHAR(length=60), nullable=True),
    sa.Column('end', sa.TIME(), nullable=True),
    sa.Column('start', sa.TIME(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index('ix_post_timestamp', ['timestamp'], unique=False)

    with op.batch_alter_table('maintenance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_timestamp'))

    op.drop_table('maintenance')
    # ### end Alembic commands ###
