"""empty message

Revision ID: eb40ea3fd1c7
Revises: 96b9d31e9663
Create Date: 2020-10-20 11:56:40.279904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb40ea3fd1c7'
down_revision = '96b9d31e9663'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_name'], ['name'])
        batch_op.drop_column('name')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=60), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=60), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###
