"""empty message

Revision ID: ebfc6834bd87
Revises: d6e24c620da8
Create Date: 2020-10-18 18:22:27.116862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebfc6834bd87'
down_revision = 'd6e24c620da8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'post', 'user', ['name'], ['name'])
    op.add_column('user', sa.Column('name', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    op.drop_constraint(None, 'post', type_='foreignkey')
    # ### end Alembic commands ###
