"""empty message

Revision ID: f551c7c2c833
Revises: ebfc6834bd87
Create Date: 2020-10-18 18:25:16.471669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f551c7c2c833'
down_revision = 'ebfc6834bd87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'post', 'user', ['name'], ['name'])
    op.add_column('user', sa.Column('name', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    op.drop_constraint(None, 'post', type_='foreignkey')
    # ### end Alembic commands ###
